apiVersion: apps/v1
kind: Deployment
metadata:
  name: cefalo-test
  labels:
    app: cefalo-app
    type: front-end
spec:
  replicas: 6
  selector:
    matchLabels:
      app: cefalo-app
      type: front-end
  template:
    metadata:
      labels:
        app: cefalo-app
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
  strategy:
    type: Recreate