apiVersion: v1
kind: Pod
metadata:
  name: cefalo-app
  labels:
    app: my-app
    type: front-end
spec:
  containers:
  - name: cefalo-app
    image: nginx
  - name: busybox-container
    image: busybox:latest
    command: ["sleep", "3600"]