apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
spec:
  containers:
  - name: random-number-container
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do shuf -i 0-100 -n 1 >> /opt/number.out; sleep 1; done"]
    volumeMounts:
    - name: data-volume
      mountPath: /opt
  volumes:
  - name: data-volume
    hostPath:
      path: /tmp/data
  securityContext:
    runAsUser: 0
